### ISSUE TITLE
Octave Executable error

### ISSUE THREAD

**Issue by adityay6895** [alshedivat/kgp#6]
Hello, 
I am unable to run the actuator code. I have renamed the file lstm-gp.py(in the screenshot). I have also attached the .bash_profile file screenshot where I have set the two environment variables OCTAVE_EXECUTABLE and GPML_PATH.
![screen shot 2017-04-27 at 12 27 56 am](https://cloud.githubusercontent.com/assets/15701251/25451769/dd22ed28-2ae0-11e7-9729-fd6768c4e84c.png)
![screen shot 2017-04-27 at 12 28 36 am](https://cloud.githubusercontent.com/assets/15701251/25451799/f5642eec-2ae0-11e7-910b-c91707279d8c.png)

**Comment by alshedivat** [comment]
Thanks for reporting the error. It looks like the issue is with your Oct2Py installation or the octave installation. Make sure the Oct2Py version is 3.9.0 and not 4.0.x -- the latter came out recently and may not be backward-compatible.

In general, Oct2Py should work as long as `octave` command is available in your terminal. I don't use the `OCTAVE_EXECUTABLE` variable in my environment. Here is a snippet from my shell rc file:
```
# MATLAB & Octave
alias matlab="/Applications/MATLAB_R2015a.app/bin/matlab -nodisplay -nosplash"
alias octave="octave --no-gui-libs"
```
